// Code generated by goyacc -o parser/parser.go parser/parser.y. DO NOT EDIT.

//line parser/parser.y:2

package parser

import __yyfmt__ "fmt"

//line parser/parser.y:3

import (
	"fmt"
	"github.com/MrHuxu/yrel/lexer"
	"strconv"
)

//line parser/parser.y:15
type yySymType struct {
	yys        int
	Void       lexer.Token
	Identifier lexer.IdToken
	Number     lexer.NumToken
	Bool       lexer.BoolToken
	String     lexer.StrToken
	Operator   string
	StmtPrefix string
	AST        ASTree
	ExprList   ExprList
}

const NUMBER = 57346
const IDENTIFIER = 57347
const BOOL = 57348
const STRING = 57349
const T_EQUAL = 57350
const T_UNEQUAL = 57351
const T_LOGIC_AND = 57352
const T_LOGIC_OR = 57353
const T_IF = 57354
const T_ELSE = 57355
const T_ELSIF = 57356
const T_WHILE = 57357
const T_PRINT = 57358
const UMINUS = 57359

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NUMBER",
	"IDENTIFIER",
	"BOOL",
	"STRING",
	"T_EQUAL",
	"T_UNEQUAL",
	"T_LOGIC_AND",
	"T_LOGIC_OR",
	"T_IF",
	"T_ELSE",
	"T_ELSIF",
	"T_WHILE",
	"T_PRINT",
	"'='",
	"'!'",
	"'>'",
	"'<'",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"UMINUS",
	"';'",
	"'('",
	"')'",
	"'{'",
	"'}'",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser/parser.y:102
/*  start  of  programs  */

var (
	Regs          = make(map[string]lexer.Token)
	Tokens        []lexer.Token
	Statements    []ASTree
	Outputs       []string
	mapStrToToken = map[string]int{
		"if":    T_IF,
		"else":  T_ELSE,
		"elsif": T_ELSIF,
		"while": T_WHILE,
		"print": T_PRINT,
	}
)

type Lexer struct {
	Input    string
	ReResult [][]string
	Line     int
	Pos      int
	Started  bool
}

func (l *Lexer) Lex(lval *yySymType) int {
	if !l.Started {
		matcher := lexer.BuildLexerMatcher()
		l.ReResult = matcher.FindAllStringSubmatch(l.Input, -1)
		l.Started = true
		l.Line = 1
	}

	// jump over all empty and line break and comment
	for l.Pos < len(l.ReResult) && (l.ReResult[l.Pos][0] == "" || l.ReResult[l.Pos][0] == "\n" || l.ReResult[l.Pos][1] != "") {
		if l.ReResult[l.Pos][0] == "\n" {
			l.Line++
		}
		if l.ReResult[l.Pos][1] != "" {
			Tokens = append(Tokens, lexer.IdToken{lexer.Util{l.Line, 1}, l.ReResult[l.Pos][1]})
			l.Line++
		}
		l.Pos++
	}

	// till the end of the lex process, return 0
	if l.Pos == len(l.ReResult) {
		return 0
	}

	matchResult := l.ReResult[l.Pos]
	l.Pos++

	if matchResult[3] != "" {
		str := matchResult[3]
		lval.String = lexer.StrToken{lexer.Util{l.Line, 3}, str[1 : len(str)-1]}
		Tokens = append(Tokens, lval.String)
		return STRING
	} else if matchResult[4] != "" {
		lval.Bool = lexer.BoolToken{lexer.Util{l.Line, 4}, matchResult[4] == "true"}
		Tokens = append(Tokens, lval.Bool)
		return BOOL
	} else if matchResult[5] != "" {
		Tokens = append(Tokens, lexer.IdToken{lexer.Util{l.Line, 5}, matchResult[5]})
		return mapStrToToken[matchResult[5]]
	} else if matchResult[6] != "" {
		num, _ := strconv.Atoi(matchResult[6])
		lval.Number = lexer.NumToken{lexer.Util{l.Line, 6}, num}
		Tokens = append(Tokens, lval.Number)
		return NUMBER
	} else if matchResult[7] != "" {
		lval.Identifier = lexer.IdToken{lexer.Util{l.Line, 7}, matchResult[7]}
		Tokens = append(Tokens, lval.Identifier)
		return IDENTIFIER
	} else if matchResult[8] != "" {
		lval.Operator = "=="
		Tokens = append(Tokens, lexer.IdToken{lexer.Util{l.Line, 8}, lval.Operator})
		return T_EQUAL
	} else if matchResult[9] != "" {
		lval.Operator = "!="
		Tokens = append(Tokens, lexer.IdToken{lexer.Util{l.Line, 9}, lval.Operator})
		return T_UNEQUAL
	} else if matchResult[10] != "" {
		Tokens = append(Tokens, lexer.IdToken{lexer.Util{l.Line, 10}, matchResult[10]})
		return int(matchResult[10][0])
	} else if matchResult[11] != "" {
		lval.Operator = "&&"
		Tokens = append(Tokens, lexer.IdToken{lexer.Util{l.Line, 10}, lval.Operator})
		return T_LOGIC_AND
	} else if matchResult[12] != "" {
		lval.Operator = "||"
		Tokens = append(Tokens, lexer.IdToken{lexer.Util{l.Line, 10}, lval.Operator})
		return T_LOGIC_OR
	}

	return -1
}

func (l *Lexer) Error(s string) {
	fmt.Println("syntax error at position", l.Line)
}

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 123

var yyAct = [...]int{

	6, 2, 65, 61, 3, 60, 63, 57, 56, 31,
	32, 33, 34, 35, 54, 54, 55, 53, 30, 37,
	38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
	48, 23, 24, 19, 20, 49, 50, 52, 27, 28,
	29, 18, 21, 22, 25, 26, 27, 28, 29, 36,
	62, 1, 51, 5, 4, 37, 14, 0, 58, 59,
	15, 13, 16, 17, 0, 64, 0, 0, 7, 0,
	0, 8, 12, 0, 10, 0, 0, 0, 11, 15,
	13, 16, 17, 0, 9, 25, 26, 27, 28, 29,
	0, 12, 0, 10, 0, 0, 0, 11, 23, 24,
	19, 20, 0, 9, 0, 23, 24, 0, 0, 21,
	22, 25, 26, 27, 28, 29, 21, 22, 25, 26,
	27, 28, 29,
}
var yyPact = [...]int{

	-1000, 56, -1000, 14, -1000, -1000, 90, -10, -19, 75,
	75, 75, 75, 32, -1000, -1000, -1000, -1000, 75, 75,
	75, 75, 75, 75, 75, 75, 75, 75, 75, 75,
	75, 75, 23, 97, 15, 90, 75, 90, 97, 97,
	64, 64, 64, 64, 15, 15, -1000, -1000, -1000, -12,
	-13, -1000, 90, -22, 75, -23, 56, 56, -26, -28,
	37, -1000, -24, 56, -29, -1000,
}
var yyPgo = [...]int{

	0, 0, 56, 1, 54, 53, 4, 51,
}
var yyR1 = [...]int{

	0, 7, 7, 3, 3, 3, 4, 4, 5, 6,
	6, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
	2, 2,
}
var yyR2 = [...]int{

	0, 0, 2, 2, 1, 1, 7, 11, 7, 1,
	3, 3, 3, 3, 2, 3, 3, 3, 3, 3,
	3, 2, 3, 3, 3, 2, 3, 1, 1, 1,
	1, 1,
}
var yyChk = [...]int{

	-1000, -7, -3, -6, -4, -5, -1, 12, 15, 28,
	18, 22, 16, 5, -2, 4, 6, 7, 27, 10,
	11, 19, 20, 8, 9, 21, 22, 23, 24, 25,
	28, 28, -1, -1, -1, -1, 17, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -6,
	-6, 29, -1, 29, 27, 29, 30, 30, -3, -3,
	31, 31, 13, 30, -3, 31,
}
var yyDef = [...]int{

	1, -2, 2, 0, 4, 5, 9, 0, 0, 0,
	0, 0, 0, 31, 27, 28, 29, 30, 3, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 14, 21, 25, 0, 10, 12, 13,
	15, 16, 17, 18, 19, 20, 22, 23, 24, 0,
	0, 11, 26, 0, 0, 0, 0, 0, 0, 0,
	6, 8, 0, 0, 0, 7,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 18, 3, 3, 3, 25, 3, 3,
	28, 29, 23, 21, 3, 22, 3, 24, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 27,
	20, 17, 19, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 30, 3, 31,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 26,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type YyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type YyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *YyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() YyParser {
	return &YyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func YyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *YyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:52
		{
			Statements = append(Statements, yyDollar[2].AST)
		}
	case 3:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:56
		{
			yyVAL.AST = yyDollar[1].ExprList
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:57
		{
			yyVAL.AST = yyDollar[1].AST
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:58
		{
			yyVAL.AST = yyDollar[1].AST
		}
	case 6:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser/parser.y:62
		{
			yyVAL.AST = IfExpr{yyDollar[3].ExprList, yyDollar[6].AST, nil}
		}
	case 7:
		yyDollar = yyS[yypt-11 : yypt+1]
//line parser/parser.y:63
		{
			yyVAL.AST = IfExpr{yyDollar[3].ExprList, yyDollar[6].AST, yyDollar[10].AST}
		}
	case 8:
		yyDollar = yyS[yypt-7 : yypt+1]
//line parser/parser.y:67
		{
			yyVAL.AST = WhileExpr{yyDollar[3].ExprList, yyDollar[6].AST}
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:71
		{
			yyVAL.ExprList = ExprList{[]ASTree{yyDollar[1].AST}}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:72
		{
			yyDollar[1].ExprList.List = append(yyDollar[1].ExprList.List, yyDollar[3].AST)
			yyVAL.ExprList = yyDollar[1].ExprList
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:76
		{
			yyVAL.AST = yyDollar[2].AST
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:77
		{
			yyVAL.AST = LogicExpr{yyDollar[1].AST, yyDollar[3].AST, "&&"}
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:78
		{
			yyVAL.AST = LogicExpr{yyDollar[1].AST, yyDollar[3].AST, "||"}
		}
	case 14:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:79
		{
			yyVAL.AST = LogicExpr{yyDollar[2].AST, ASTLeaf{nil}, "!"}
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:80
		{
			yyVAL.AST = CompExpr{yyDollar[1].AST, yyDollar[3].AST, ">"}
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:81
		{
			yyVAL.AST = CompExpr{yyDollar[1].AST, yyDollar[3].AST, "<"}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:82
		{
			yyVAL.AST = CompExpr{yyDollar[1].AST, yyDollar[3].AST, "=="}
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:83
		{
			yyVAL.AST = CompExpr{yyDollar[1].AST, yyDollar[3].AST, "!="}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:84
		{
			yyVAL.AST = CalcExpr{yyDollar[1].AST, yyDollar[3].AST, "+"}
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:85
		{
			yyVAL.AST = CalcExpr{yyDollar[1].AST, yyDollar[3].AST, "-"}
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:86
		{
			yyVAL.AST = CalcExpr{yyDollar[2].AST, ASTLeaf{nil}, "Neg"}
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:87
		{
			yyVAL.AST = CalcExpr{yyDollar[1].AST, yyDollar[3].AST, "*"}
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:88
		{
			yyVAL.AST = CalcExpr{yyDollar[1].AST, yyDollar[3].AST, "/"}
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:89
		{
			yyVAL.AST = CalcExpr{yyDollar[1].AST, yyDollar[3].AST, "%"}
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser/parser.y:90
		{
			yyVAL.AST = PrintExpr{nil, yyDollar[2].AST, "print"}
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser/parser.y:91
		{
			yyVAL.AST = DefExpr{yyDollar[1].Identifier, yyDollar[3].AST, "="}
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:96
		{
			yyVAL.AST = ASTLeaf{yyDollar[1].Number}
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:97
		{
			yyVAL.AST = ASTLeaf{yyDollar[1].Bool}
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:98
		{
			yyVAL.AST = ASTLeaf{yyDollar[1].String}
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser/parser.y:99
		{
			yyVAL.AST = IdExpr{yyDollar[1].Identifier}
		}
	}
	goto yystack /* stack new state and value */
}
